# Generated by Django 2.1 on 2018-09-25 22:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=124)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expense_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('category', models.CharField(choices=[('Julita', 'Julita'), ('Dawid', 'Dawid')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('slug', models.SlugField(blank=True, max_length=124, unique=True)),
                ('budget', models.IntegerField()),
                ('photo', models.ImageField(null=True, upload_to='months')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budget.Project'),
        ),
    ]
